### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Miezaru/bootstrapkinozal3.4#1]
1)
Нет скруглений
![image](https://user-images.githubusercontent.com/8464662/78550802-686b6c80-780d-11ea-886e-5c52f2830d59.png)

2)
шрифт, отступы
![image](https://user-images.githubusercontent.com/8464662/78550819-71f4d480-780d-11ea-898a-00afffcb8abf.png)

3)
шрифт 
![image](https://user-images.githubusercontent.com/8464662/78550871-8769fe80-780d-11ea-9a78-ef04dff50812.png)

4)
текст
![image](https://user-images.githubusercontent.com/8464662/78550906-90f36680-780d-11ea-9df6-4f02187f6b76.png)

5)
отступ
![image](https://user-images.githubusercontent.com/8464662/78550979-aa94ae00-780d-11ea-8c1d-a7f0ec19d7e0.png)

6)
отступы
![image](https://user-images.githubusercontent.com/8464662/78551021-b8e2ca00-780d-11ea-90dc-e61f507bd775.png)

7)
размеры, пропорции
![image](https://user-images.githubusercontent.com/8464662/78551079-cef08a80-780d-11ea-9c3a-ffa1a52c204f.png)

8)
обрывы
![image](https://user-images.githubusercontent.com/8464662/78551128-dfa10080-780d-11ea-9922-8bd167a7b0f6.png)
![image](https://user-images.githubusercontent.com/8464662/78551165-ef204980-780d-11ea-8353-a292e7fb7be6.png)

9)
обрывы
![image](https://user-images.githubusercontent.com/8464662/78551208-fcd5cf00-780d-11ea-99c9-09bc040dbc5a.png)

**Comment by Alecto** [comment]
10)
невалидный код
![image](https://user-images.githubusercontent.com/8464662/78551244-0d864500-780e-11ea-920a-f5fb8514dce1.png)
![image](https://user-images.githubusercontent.com/8464662/78551288-1d058e00-780e-11ea-9d30-937fa2f9ed3e.png)

**Comment by Alecto** [comment]
6, 7, 8 - не исправлено

**Comment by Alecto** [comment]
7)
![image](https://user-images.githubusercontent.com/8464662/78741451-05d7b500-7962-11ea-9bad-9afc0b5da2d6.png)

**Comment by Alecto** [comment]
не исправлено

**Comment by Alecto** [comment]
некорректный внешний вид, отступы
![image](https://user-images.githubusercontent.com/8464662/79302456-1a352800-7ef5-11ea-81c9-e420852e84bb.png)

**Comment by Alecto** [comment]
не исправлено

**Comment by Alecto** [comment]
скриню результат - не исправлено
![image](https://user-images.githubusercontent.com/8464662/79483265-be64bf00-801a-11ea-972c-c1cf8bafca6e.png)

**Comment by Miezaru** [comment]
Ошибки исправил. проект защитил.
